analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - ios/**
    - android/**
    - macos/**
    - web/**
    - lib/**.*.dart
    - test/**.*.dart
    - "lib/firebase_options.dart"
  errors:
    invalid_annotation_target: ignore #https://github.com/rrousselGit/freezed/issues/488
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true