name: product_app
description: "List of products"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.2
  http: ^1.2.2
  dart_mappable_builder: ^4.2.3
  injectable: ^2.4.4
  injectable_generator: ^2.6.2
  flutter_bloc: ^8.1.6
  retrofit: ^4.4.1
  dio: ^5.7.0
  get_it: ^7.7.0
  meta: ^1.12.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/