name: Ci for prs against main

on:
  pull_request:
    branches:
      - develop

jobs:
  quality-check:
    name: Run Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Flutter Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Flutter Version
        run: flutter --version

      - name: Get Dependencies
        run: flutter pub get

      - name: Check Dart Formatting
        run: dart format . --set-exit-if-changed

      - name: Generate Files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Static Analysis
        run: |
          ANALYSIS_RESULTS=$(dart analyze)
          echo "$ANALYSIS_RESULTS"
          if [[ "$ANALYSIS_RESULTS" == *"No issues found!"* ]]; then
              echo "Static analysis found no issues."
              exit 0
          else
              echo "Static analysis found issues."
              exit 1
          fi